$FirebaseSDKVersion = '10.29.0'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

# Enable modular headers globally
use_modular_headers!

flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']

if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SamuApp' do
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path, :modular_headers => true
  pod 'Google-Maps-iOS-Utils', :modular_headers => true
  
  # Firebase dependencies
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Analytics', :modular_headers => true
  pod 'Firebase/Auth', :modular_headers => true
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'
  
  pod 'react-native-appsflyer',:path => '../node_modules/react-native-appsflyer'

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'SamuAppTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Set deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        
        # Default architecture settings
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        
        # Handle specific targets
        case target.name
        when 'Paystack'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          config.build_settings['VALID_ARCHS'] = 'x86_64'
        when 'react-native-geolocation-service'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
          config.build_settings['VALID_ARCHS'] = 'x86_64 arm64'
        else
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
          config.build_settings['VALID_ARCHS'] = 'x86_64 arm64'
        end
      end
    end

    bitcode_strip_path = `xcrun --find bitcode_strip`.chomp
    unless bitcode_strip_path.empty?
      def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
        framework_path = File.join(Dir.pwd, framework_relative_path)
        if File.exist?(framework_path)
          command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
          puts "Stripping bitcode: #{command}"
          system(command)
        else
          puts "Framework not found at path: #{framework_path}, skipping bitcode strip."
        end
      end

      framework_paths = [
        # Add Zendesk Framework Path
        "Pods/ZendeskSDKLogger/ZendeskSDKLogger.xcframework/ios-arm64/ZendeskSDKLogger.framework/ZendeskSDKLogger",
        # Other frameworks
        "Pods/LogRocket/LogRocket.xcframework/ios-arm64/LogRocket.framework/LogRocket",
        "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/macosx/hermes.framework/Versions/Current/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes",
        "Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/hermes"
      ]

      framework_paths.each do |framework_relative_path|
        strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      end
    else
      puts "bitcode_strip tool not found, skipping bitcode stripping."
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '= 5.2.4'
end
