import {NEW_GOOGLE_MAPS_API_KEY} from '@env';
import { Social } from 'react-native-share';
import {getBaseUrlFromStorage} from 'src/utils/SetENV';

export const APIRoutes = {
  ThirdParty: {
    ReverseGeocode: `https://maps.googleapis.com/maps/api/geocode/json?latlng={lat},{lng}&key=${NEW_GOOGLE_MAPS_API_KEY}`,
  },
  User: {
    SignUp: () => `${getBaseUrlFromStorage()}/user/auth/register`,
    LoginWithEmail: () => `${getBaseUrlFromStorage()}/user/auth/login`,
    LoginWithPhone: () => `${getBaseUrlFromStorage()}/user/auth/login/phone`,
    EamilVerify: () => `${getBaseUrlFromStorage()}/user/auth/email-verify`,
    PhoneVerify: () => `${getBaseUrlFromStorage()}/user/auth/phone-verify`,
    PhoneConfirm: () => `${getBaseUrlFromStorage()}/user/auth/phone-confirm`,
    LoginPhoneConfirm: () => `${getBaseUrlFromStorage()}/user/auth/login/phone-confirm`,
    Address: () => `${getBaseUrlFromStorage()}/user/address`,
    UpdateAddress: () => `${getBaseUrlFromStorage()}/user/address/:addressId`,
    ResetPassword: () => `${getBaseUrlFromStorage()}/user/auth/reset-password`,
    UpdateDeleteAddress: () => `${getBaseUrlFromStorage()}/user/address/:addressId`,
    ChangePassword: () => `${getBaseUrlFromStorage()}/me/change-password`,
    Me: () => `${getBaseUrlFromStorage()}/me`,
    Collections: () => `${getBaseUrlFromStorage()}/user/collections`,
    BrowsePage: () => `${getBaseUrlFromStorage()}/user/page/browse`,
    searchAll: () => `${getBaseUrlFromStorage()}/user/search?keyword=`,
    homeData: () => `${getBaseUrlFromStorage()}/user/page/home`,
    exploreData: () => `${getBaseUrlFromStorage()}/user/page/explore`,
    searchProduct: () => `${getBaseUrlFromStorage()}/user/search/product?keyword=`,
    universalSearch: () => `${getBaseUrlFromStorage()}/user/search/universal`,
    storeDetails: () => `${getBaseUrlFromStorage()}/user/store`,
    storeMenu: () => `${getBaseUrlFromStorage()}/user/store/menus/:storeId`,
    storeProduct: () => `${getBaseUrlFromStorage()}/user/product/store/:storeId`,
    storeProductDetails: () => `${getBaseUrlFromStorage()}/user/product/:productId`,
    searchStores: () => `${getBaseUrlFromStorage()}/user/search/store`,
    productAddToCart: () => `${getBaseUrlFromStorage()}/user/cart/addProduct`,
    productGetCart: () => `${getBaseUrlFromStorage()}/user/cart/latest`,
    productUpdateCart: () => `${getBaseUrlFromStorage()}/user/cart/:productCartId`,
    productRemoveCart: () => `${getBaseUrlFromStorage()}/user/cart/product/:productCartId`,
    updateCartAddress: () => `${getBaseUrlFromStorage()}/user/cart/:cartId/address`,
    productClearCart: () => `${getBaseUrlFromStorage()}/user/cart/:cartId`,
    getAllPaymentMethods: () => `${getBaseUrlFromStorage()}/user/payment-method`,
    getInitiatePayment: () => `${getBaseUrlFromStorage()}/user/payment/initate/:cartId`,
    setupPaymentCharge: () => `${getBaseUrlFromStorage()}/user/payment/charge`,
    setupCheckout: () => `${getBaseUrlFromStorage()}/user/order`,
    addNewPaymentMethod: () => `${getBaseUrlFromStorage()}/user/payment-method/card`,
    setupPaymentDefault: () => `${getBaseUrlFromStorage()}/user/payment-method/default/:paymentMethodId`,
    updatePaymentMethod: () => `${getBaseUrlFromStorage()}/user/order/:orderId/payment-method`,
    checkOrderPaid: () => `${getBaseUrlFromStorage()}/user/order/:orderId/paid`,
    paymentCalculated: () => `${getBaseUrlFromStorage()}/user/order/calculatePaymentAmount`,
    getOrderDetails: () => `${getBaseUrlFromStorage()}/user/order/:orderId`,
    getAllOrders: () => `${getBaseUrlFromStorage()}/user/order?page={page}&pageSize={pageSize}&status={status}&sortBy={sortBy}`,
    cancelOrder: () => `${getBaseUrlFromStorage()}/user/order/cancel/:orderId`,
    browseGrid: () => `${getBaseUrlFromStorage()}/user/page/productCollections`,
    socialAuth: () => `${getBaseUrlFromStorage()}/user/auth/register/social`,
    pageOpened: () => `${getBaseUrlFromStorage()}/user/analytics/pageOpened`,
    searchPlaced: () => `${getBaseUrlFromStorage()}/user/analytics/searchPlaced`,
    searchResult: () => `${getBaseUrlFromStorage()}/user/analytics/searchResult`,
    storePageView: () => `${getBaseUrlFromStorage()}/user/analytics/storePageView`,
    viewProduct: () => `${getBaseUrlFromStorage()}/user/analytics/viewProduct`,
    addToCart: () => `${getBaseUrlFromStorage()}/user/analytics/addToCart`,
    cartPage: () => `${getBaseUrlFromStorage()}/user/analytics/cartPage`,
    beginAddingPaymentMethod: () => `${getBaseUrlFromStorage()}/user/analytics/beginAddingPaymentMethod`,
    paymentMethodAdded: () => `${getBaseUrlFromStorage()}/user/analytics/paymentMethodAdded`,
    tipSet: () => `${getBaseUrlFromStorage()}/user/analytics/tipSet`,
    checkoutStarted: () => `${getBaseUrlFromStorage()}/user/analytics/checkoutStarted`,
    checkoutFailed: () => `${getBaseUrlFromStorage()}/user/analytics/checkoutFailed`,
    checkoutCompleted: () => `${getBaseUrlFromStorage()}/user/analytics/checkoutCompleted`,
    productSearchbyStore: () => `${getBaseUrlFromStorage()}/user/search/product/store/:storeId?keyword=`,
    helpDesk: () => `${getBaseUrlFromStorage()}/user/zendesk`,
    guestMode: () => `${getBaseUrlFromStorage()}/user/auth/login/device`,
  },
};
