export enum AuthenticationType {
  Register = 'register',
  EmailLogin = 'emailLogin',
  PhoneLogin = 'phoneLogin',
  googleLogin='googleLogin',
  appleLogin='appleLogin',
}

export const addressInitialState = {
  name: '',
  primary: false,
  street: '',
  street2: '',
  unit: '',
  city: '',
  zip: '',
  province: '',
  country: '',
  geometry: '',
  typeOfPlace: '',
  deliveryNotes: '',
};

export const userInitialState: userInitialStateUserState = {
  id: '',
  uuid: '',
  user: {

    addresses: [],
    isSuspended: false,
    firstName: '',
    lastName: '',
    dateOfBirth: '',
    gender: '',
    email: '',
    phone: '',
    emailVerified: false,
    phoneVerified: false,
    createdAt: new Date().toISOString(),
    upstringdAt: new Date().toISOString(),
    id: '',
  },
  addressForm: {...addressInitialState},
  firstName: '',
  lastName: '',
  dateOfBirth: '',
  gender: '',
  email: '',
  phone: '',
  emailVerified: false,
  phoneVerified: false,
  password: '',
  confirmationPassword: '',
  accessToken: '',
  isLoggedIn: false,
  authenticationType: undefined,
  updateDone: false,
  deleteDone: false,
  verifiedPhone: '',
  resetPasswordRequested: false,
  isLoading: false,
  searchKey: '',
  error: null,
  isGuest: false,
  // update profile
  updateProfileData: {},
  isUpdateProfileLoading: false,
  isSelectHelpIsLoading:false,
  updateProfileError: null,
  userCancelled:false,

};
